AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  handleCreate



Resources:
  handleCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handleCreate/index.handleCreate
      Runtime: nodejs18.x

#   ProcessDynamoDBStream:
#   Type: AWS::Serverless::Function
#   Properties:
#     Handler: src/handleCreate/index.handleCreate
#     Runtime: nodejs18.x
#     Policies: AWSLambdaDynamoDBExecutionRole
#     Events:
#       Stream:
#         Type: DynamoDB
#         Properties:
#           Stream: !GetAtt DynamoDBTable.StreamArn
#           BatchSize: 100
#           StartingPosition: TRIM_HORIZON

# DynamoDBTable:
#   Type: AWS::DynamoDB::Table
#   Properties: 
#     AttributeDefinitions: 
#       - AttributeName: id
#         AttributeType: S
#     KeySchema: 
#       - AttributeName: id
#         KeyType: HASH
#     ProvisionedThroughput: 
#       ReadCapacityUnits: 5
#       WriteCapacityUnits: 5
#     StreamSpecification:
#       StreamViewType: NEW_IMAGE