name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Zip up project
        run: |
          zip -r create.zip ./src/handleCreate/ ./node_modules ./src/package.json ./package-lock.json
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          zip_file: create.zip
          function_name: handleCreate
          runtime: nodejs18.x